import { Colors, Spacing, Typography } from '@/constants/theme';
import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

// MANDATORY PRESERVATION LIST: Layout Constants
export const ITEM_WIDTH = width * 0.48;
export const SPACER_WIDTH = (width - ITEM_WIDTH) / 2;
export const CIRCLE_SIZE = 180;
export const SIDE_CIRCLE_SIZE = 120;
export const ACTIVE_TAB_SVG = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='32' viewBox='0 0 40 32'%3E%3Cpath d='M 0 32 Q 8 32 8 24 L 8 12 A 12 12 0 0 1 32 12 L 32 24 Q 32 32 40 32 Z' fill='white' /%3E%3C/svg%3E`;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.white,
    },
    topNav: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 50,
        paddingBottom: Spacing.sm,
        zIndex: 30,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
    },
    navButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Typography.h3,
        color: Colors.white,
        fontWeight: '700',
    },
    contentContainer: {
        backgroundColor: Colors.white,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        marginTop: -24,
        paddingTop: 24,
        paddingBottom: 40,
        minHeight: height * 0.6,
    },
    scrollContent: {
        flexGrow: 1,
    },
    heroSection: {
        backgroundColor: Colors.surface,
        height: width * 0.76,
        paddingTop: 30,
        paddingBottom: 15,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    carouselContent: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    birdSlide: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    mainCircle: {
        width: CIRCLE_SIZE,
        height: CIRCLE_SIZE,
        borderRadius: CIRCLE_SIZE / 2,
        backgroundColor: Colors.white,
        borderWidth: 2,
        borderColor: Colors.white,
        overflow: 'hidden',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 10,
    },
    circleImage: {
        width: '100%',
        height: '100%',
    },
    thumbnailContainer: {
        position: 'absolute',
        bottom: 50,
        left: 16,
        width: 85,
        height: 54,
        borderRadius: 0,
        borderWidth: 1,
        borderColor: Colors.white,
        overflow: 'hidden',
        zIndex: 20,
        backgroundColor: Colors.surface,
    },
    thumbnailImage: {
        width: '100%',
        height: '100%',
    },
    pagination: {
        flexDirection: 'row',
        position: 'absolute',
        bottom: 32,
        left: 0,
        right: 0,
        gap: 8,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 50,
    },
    tabIndicator: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: Colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    activeTab: {
        borderWidth: 1.5,
        borderColor: Colors.primary,
    },
    activeTabBackground: {
        ...StyleSheet.absoluteFillObject,
    },
    tabText: {
        ...Typography.label,
        color: '#666',
        fontSize: 13,
        fontWeight: '700',
    },
    activeTabText: {
        color: Colors.primary,
        fontSize: 16,
        fontWeight: '800',
    },
    correctionSection: {
        padding: 24,
        alignItems: 'center',
        backgroundColor: Colors.surfaceLight,
        margin: 20,
        borderRadius: 24,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: Colors.textSecondary + '33',
    },
    correctionTitle: {
        ...Typography.h2,
        color: Colors.text,
        marginBottom: 12,
        textAlign: 'center',
    },
    correctionText: {
        ...Typography.body,
        color: Colors.textSecondary,
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
    },
    correctBtn: {
        backgroundColor: Colors.primary,
        paddingHorizontal: 32,
        paddingVertical: 16,
        borderRadius: 30,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
        alignSelf: 'center',
    },
    correctBtnText: {
        color: Colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 90,
        backgroundColor: Colors.white,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingBottom: 25,
        borderTopWidth: 1,
        borderTopColor: Colors.surfaceLight,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
    },
    actionItem: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
    },
    actionText: {
        fontSize: 12,
        fontWeight: '600',
        color: Colors.text,
    },
    contentSection: {
        paddingTop: Spacing.lg,
    },
    savedBadge: {
        width: 140,
        height: 140,
        borderRadius: 70,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 15,
    },
    savedBadgeBlur: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    savedBadgeContent: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    savedIconCircle: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: Colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 5,
    },
    savedBadgeText: {
        ...Typography.h3,
        color: Colors.white,
        fontWeight: '800',
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    listenBackContainer: {
        position: 'absolute',
        bottom: 32,
        left: 8,
        zIndex: 60,
    },
});
